channel: stable
addons:
  laskakit-data-feeder:
    repository: radoslavirha/ha-addon-laskakit-data-feeder
    target: laskakit-data-feeder
    image: radoslavirha/ha-addon-laskakit-data-feeder-{arch}