---
name: Repository Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["update"]

jobs:
  workflows:
    name: Running updater for ${{ github.event.client_payload.addon }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Repository Updater
        uses: hassio-addons/repository-updater@v1
        with:
          # addon: ${{ github.event.client_payload.addon }}
          addon: laskakit-data-feeder
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}

  # workflows:
  #   uses: hassio-addons/workflows/.github/workflows/repository-updater.yaml@main
  #   secrets:
  #     UPDATER_TOKEN: ${{ secrets.UPDATER_TOKEN }}