---
name: Repository Update

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      ADDON:
        description: Addon name
        required: true
        default: laskakit-data-feeder
        type: string
      FORCE:
        description: Whether to update all add-ons
        required: false
        default: false
        type: boolean
  repository_dispatch:
    types: ["update"]

jobs:
  updater:
    name: Running repository updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Running repository updater
        uses: ./.github/actions/repository-updater
        with:
          TOKEN: ${{ secrets.UPDATER_TOKEN }}
          ADDON: ${{ github.event.client_payload.addon || github.event.inputs.ADDON }}
          FORCE: ${{ github.event.inputs.FORCE }}
